sudo: false

language: ruby
rvm:
- 2.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

install:
  - npm install
  - gem install jekyll jekyll-paginate html-proofer

script:
  - npm run gulp build
  - rm -R ./_site/node_modules
  - htmlproofer ./_site --disable-external
