name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: HTML Proofer
        uses: chabad360/htmlproofer@master
        with:
          directory: "./public" # The directory to scan
          arguments: --allow_hash_href --url-ignore (.*lifelongstudent.io.*|.*galon.io.*)
